---
- name: memcached
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'memcached_selection'
      prompt: "\nPlease choose the number for Memcached version [ 1/2/3 ] \n\n
      1: Memcached1.6\n
      2: Memcached1.5\n
      3: Memcached1.4\n"
      private: no
      default: 1
  
  vars:
    memcached_select:
      '1': '1.6'
      '2': '1.5'
      '3': '1.4'

    memcached_version: "{{memcached_select[memcached_selection]}}" 

  roles:
<<<<<<< HEAD
    - { role: role_common, tags: "role_common"} 
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_docker , tags: "role_docker"}
    - { role: memcached, tags: "memcached"}
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end" }

=======
  - { role: role_common , tags: "role_common"} 
  - { role: role_cloud , tags: "role_cloud"} 
  - { role: role_docker , tags: "role_docker"} 
  - { role: role_memcached , tags: "role_memcached"}
  - { role: memcached , tags: "memcached"}
  - { role: role_nginx , tags: "role_nginx"}
  - { role: role_init , tags: "role_init"}  
  - { role: role_preend  , tags: "role_preend"}  
  - { role: role_end  , tags: "role_end"}
>>>>>>> dev
