- name: Delete memcached dir for sec_installation
  shell: rm -rf {{memcached_work_dir}}

- name: Clone memcached in Websoft9 
  git:
    repo: "{{memcached_git_url}}"
    dest: "{{memcached_work_dir}}"

- name: Rename compose and env filename
  shell: |
    rm -rf docker-compose.yml
    [ -f docker-compose-production.yml ] && mv docker-compose-production.yml docker-compose.yml
    [ -f .env_all ] && mv .env_all .env
    sed -i 's/APP_VERSION=.*/APP_VERSION=v{{memcached_version}}/g' /data/apps/memcached/.env
  args:
    chdir: '{{memcached_work_dir}}'
    
- name: Run docker-compose 
  shell: | 
    docker-compose up -d
    sleep 30
  args:
    chdir: '{{memcached_work_dir}}'

# check service and version
- name: Check memcached service 
  shell: >
    docker ps -a |awk '{print $2,$7}'
  register: check_memcached_service
  notify: check_memcached_service
    
- name: Check memcached version
  shell: |
    sudo echo "memcached version:" $(docker images |grep memcached |cut -d- -f4) |sudo tee -a /data/logs/install_version.txt 
