---
# install memadmin
- name: Clone memadmin in Websoft9 
  git:
    repo: "{{memadmin_git_url}}"
    dest: "/data/apps/memadmin"

- name: Rename filename and Run memadmin using docker-compose
  shell: |
    [ -f docker-compose-production.yml ] && mv docker-compose-production.yml docker-compose.yml
    [ -f .env_all ] && mv .env_all .env
    sed -i '/APP_PORT=/s/9090/127.0.0.1:9099/g' .env
    docker-compose up -d
  args:
    chdir: /data/apps/memadmin

# check version
- name: check memcached version
  shell: sudo echo "memcached version:" `docker inspect hatamiarash7/memcached-admin |grep VERSION |cut -d = -f2 |awk  'NR==1' ` |tee -a /data/logs/install_version.txt

# check service state
- name: Check memadmin Service     
  shell: docker ps |grep memadmin
  register: check_memadmin_service
  notify: check_memadmin_service
